// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBanHQ-uUmJlFYyMw8OqgaaBmn89Tf5PgQ',
    appId: '1:133641593979:android:14f957e5c1f5321433aede',
    messagingSenderId: '133641593979',
    projectId: 'harves-young',
    databaseURL: 'https://harves-young-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harves-young.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAil_X1qr4rMvqBfW1wfH4I573qF9SoX30',
    appId: '1:133641593979:ios:265ac98761228a2433aede',
    messagingSenderId: '133641593979',
    projectId: 'harves-young',
    databaseURL: 'https://harves-young-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'harves-young.firebasestorage.app',
    iosClientId: '133641593979-l5j8eklk8em4kndb25j81fd2lbt7f81a.apps.googleusercontent.com',
    iosBundleId: 'com.example.rate',
  );

}