

const List<Map<String, String>> asianCountries = [
  {"code": "af", "name": "Afghanistan", "currency": "AFN"},
  {"code": "am", "name": "Armenia", "currency": "AMD"},
  {"code": "az", "name": "Azerbaijan", "currency": "AZN"},
  {"code": "bh", "name": "Bahrain", "currency": "BHD"},
  {"code": "bd", "name": "Bangladesh", "currency": "BDT"},
  {"code": "bt", "name": "Bhutan", "currency": "BTN"},
  {"code": "bn", "name": "Brunei", "currency": "BND"},
  {"code": "kh", "name": "Cambodia", "currency": "KHR"},
  {"code": "cn", "name": "China", "currency": "CNY"},
  {"code": "cy", "name": "Cyprus", "currency": "EUR"},
  {"code": "ge", "name": "Georgia", "currency": "GEL"},
  {"code": "hk", "name": "Hong Kong (China)", "currency": "HKD"},
  {"code": "in", "name": "India", "currency": "INR"},
  {"code": "id", "name": "Indonesia", "currency": "IDR"},
  {"code": "ir", "name": "Iran", "currency": "IRR"},
  {"code": "iq", "name": "Iraq", "currency": "IQD"},
  {"code": "il", "name": "Israel", "currency": "ILS"},
  {"code": "jp", "name": "Japan", "currency": "JPY"},
  {"code": "jo", "name": "Jordan", "currency": "JOD"},
  {"code": "kz", "name": "Kazakhstan", "currency": "KZT"},
  {"code": "kw", "name": "Kuwait", "currency": "KWD"},
  {"code": "kg", "name": "Kyrgyzstan", "currency": "KGS"},
  {"code": "la", "name": "Laos", "currency": "LAK"},
  {"code": "lb", "name": "Lebanon", "currency": "LBP"},
  {"code": "mo", "name": "Macau (China)", "currency": "MOP"},
  {"code": "my", "name": "Malaysia", "currency": "MYR"},
  {"code": "mv", "name": "Maldives", "currency": "MVR"},
  {"code": "mn", "name": "Mongolia", "currency": "MNT"},
  {"code": "mm", "name": "Myanmar", "currency": "MMK"},
  {"code": "np", "name": "Nepal", "currency": "NPR"},
  {"code": "kp", "name": "North Korea", "currency": "KPW"},
  {"code": "om", "name": "Oman", "currency": "OMR"},
  {"code": "pk", "name": "Pakistan", "currency": "PKR"},
  {"code": "ph", "name": "Philippines", "currency": "PHP"},
  {"code": "qa", "name": "Qatar", "currency": "QAR"},
  {"code": "ru", "name": "Russia", "currency": "RUB"},
  {"code": "sa", "name": "Saudi Arabia", "currency": "SAR"},
  {"code": "sg", "name": "Singapore", "currency": "SGD"},
  {"code": "kr", "name": "South Korea", "currency": "KRW"},
  {"code": "lk", "name": "Sri Lanka", "currency": "LKR"},
  {"code": "sy", "name": "Syria", "currency": "SYP"},
  {"code": "tw", "name": "Taiwan (China)", "currency": "TWD"},
  {"code": "tj", "name": "Tajikistan", "currency": "TJS"},
  {"code": "th", "name": "Thailand", "currency": "THB"},
  {"code": "tr", "name": "Turkey", "currency": "TRY"},
  {"code": "tm", "name": "Turkmenistan", "currency": "TMT"},
  {"code": "ae", "name": "United Arab Emirates", "currency": "AED"},
  {"code": "uz", "name": "Uzbekistan", "currency": "UZS"},
  {"code": "vn", "name": "Vietnam", "currency": "VND"},
  {"code": "ye", "name": "Yemen", "currency": "YER"}
];


const List<Map<String, String>> europeanCountries = [
  {"code": "al", "name": "Albania", "currency": "ALL"},
  {"code": "am", "name": "Armenia", "currency": "AMD"},
  {"code": "az", "name": "Azerbaijan", "currency": "AZN"},
  {"code": "ba", "name": "Bosnia and Herzegovina", "currency": "BAM"},
  {"code": "bg", "name": "Bulgaria", "currency": "BGN"},
  {"code": "cz", "name": "Czechia", "currency": "CZK"},
  {"code": "dk", "name": "Denmark", "currency": "DKK"},
  {"code": "eu", "name": "Europe Union", "currency": "EUR"},
  {"code": "ge", "name": "Georgia", "currency": "GEL"},
  {"code": "hu", "name": "Hungary", "currency": "HUF"},
  {"code": "is", "name": "Iceland", "currency": "ISK"},
  {"code": "kz", "name": "Kazakhstan", "currency": "KZT"},
  {"code": "li", "name": "Liechtenstein", "currency": "CHF"},
  {"code": "md", "name": "Moldova", "currency": "MDL"},
  {"code": "mk", "name": "North Macedonia", "currency": "MKD"},
  {"code": "no", "name": "Norway", "currency": "NOK"},
  {"code": "pl", "name": "Poland", "currency": "PLN"},
  {"code": "ro", "name": "Romania", "currency": "RON"},
  {"code": "ru", "name": "Russia", "currency": "RUB"},
  {"code": "rs", "name": "Serbia", "currency": "RSD"},
  {"code": "se", "name": "Sweden", "currency": "SEK"},
  {"code": "ch", "name": "Switzerland", "currency": "CHF"},
  {"code": "ua", "name": "Ukraine", "currency": "UAH"},
  {"code": "gb", "name": "United Kingdom", "currency": "GBP"},
];


const List<Map<String, String>> africanCountries = [
  {"code": "dz", "name": "Algeria", "currency": "DZD"},
  {"code": "ao", "name": "Angola", "currency": "AOA"},
  {"code": "bj", "name": "Benin", "currency": "XOF"},
  {"code": "bw", "name": "Botswana", "currency": "BWP"},
  {"code": "bf", "name": "Burkina Faso", "currency": "BFA"},
  {"code": "bi", "name": "Burundi", "currency": "BIF"},
  {"code": "cm", "name": "Cameroon", "currency": "XAF"},
  {"code": "cv", "name": "Cape Verde", "currency": "CVE"},
  {"code": "cf", "name": "Central African Republic", "currency": "BFA"},
  {"code": "td", "name": "Chad", "currency": "BFA"},
  {"code": "cd", "name": "DR Congo", "currency": "CDF"},
  {"code": "km", "name": "Comoros", "currency": "KMF"},
  {"code": "cg", "name": "Republic of the Congo", "currency": "CDF"},
  {"code": "dj", "name": "Djibouti", "currency": "DJF"},
  {"code": "eg", "name": "Egypt", "currency": "EGP"},
  {"code": "gq", "name": "Equatorial Guinea", "currency": "GNF"},
  {"code": "er", "name": "Eritrea", "currency": "ERN"},
  {"code": "et", "name": "Ethiopia", "currency": "ETB"},
  {"code": "ga", "name": "Gabon", "currency": "CDF"},
  {"code": "gh", "name": "Ghana", "currency": "GHS"},
  {"code": "gn", "name": "Guinea", "currency": "GNF"},
  {"code": "gw", "name": "Guinea-Bissau", "currency": "GNF"},
  {"code": "ke", "name": "Kenya", "currency": "KES"},
  {"code": "lr", "name": "Liberia", "currency": "LRD"},
  {"code": "ly", "name": "Libya", "currency": "LYD"},
  {"code": "ma", "name": "Morocco", "currency": "MAD"},
  {"code": "mz", "name": "Mozambique", "currency": "MZN"},
  {"code": "na", "name": "Namibia", "currency": "NAD"},
  {"code": "ne", "name": "Niger", "currency": "NGN"},
  {"code": "ng", "name": "Nigeria", "currency": "NGN"},
  {"code": "rw", "name": "Rwanda", "currency": "RWF"},
  {"code": "sd", "name": "Sudan", "currency": "SDG"},
  {"code": "sl", "name": "Sierra Leone", "currency": "SLL"},
  {"code": "sn", "name": "Senegal", "currency": "XOF"},
  {"code": "so", "name": "Somalia", "currency": "SOS"},
  {"code": "za", "name": "South Africa", "currency": "ZAR"},
  {"code": "ss", "name": "South Sudan", "currency": "SSP"},
  {"code": "tz", "name": "Tanzania", "currency": "TZS"},
  {"code": "ne", "name": "Togo", "currency": "XOF"},
  {"code": "ug", "name": "Uganda", "currency": "UGX"},
  {"code": "zm", "name": "Zambia", "currency": "ZMW"},
  {"code": "zw", "name": "Zimbabwe", "currency": "ZWL"},
];


const List<Map<String, String>> northAmericanCountries = [
  {"code": "bz", "name": "Belize", "currency": "BZD"},
  {"code": "ca", "name": "Canada", "currency": "CAD"},
  {"code": "cr", "name": "Costa Rica", "currency": "CRC"},
  {"code": "gt", "name": "Guatemala", "currency": "GTQ"},
  {"code": "hn", "name": "Honduras", "currency": "HNL"},
  {"code": "mx", "name": "Mexico", "currency": "MXN"},
  {"code": "ni", "name": "Nicaragua", "currency": "NIO"},
  {"code": "pa", "name": "Panama", "currency": "PAB"},
  {"code": "sv", "name": "El Salvador", "currency": "SVC"},
  {"code": "us", "name": "United States", "currency": "USD"},
];

const List<Map<String, String>> southAmericanCountries = [
  {"code": "ar", "name": "Argentina", "currency": "ARS"},
  {"code": "bo", "name": "Bolivia", "currency": "BOB"},
  {"code": "br", "name": "Brazil", "currency": "BRL"},
  {"code": "cl", "name": "Chile", "currency": "CLP"},
  {"code": "co", "name": "Colombia", "currency": "COP"},
  {"code": "ec", "name": "Ecuador", "currency": "USD"},
  {"code": "gy", "name": "Guyana", "currency": "GYD"},
  {"code": "py", "name": "Paraguay", "currency": "PYG"},
  {"code": "pe", "name": "Peru", "currency": "PEN"},
  {"code": "sr", "name": "Suriname", "currency": "SRD"},
  {"code": "uy", "name": "Uruguay", "currency": "UYU"},
  {"code": "ve", "name": "Venezuela", "currency": "VES"},
];


const List<Map<String, String>> oceaniaCountries = [
  {"code": "au", "name": "Australia", "currency": "AUD"},
  {"code": "fj", "name": "Fiji", "currency": "FJD"},
  {"code": "ki", "name": "Kiribati", "currency": "AUD"},
  {"code": "mh", "name": "Marshall Islands", "currency": "USD"},
  {"code": "fm", "name": "Micronesia", "currency": "USD"},
  {"code": "mo", "name": "Macau", "currency": "MOP"},
  {"code": "nr", "name": "Nauru", "currency": "AUD"},
  {"code": "nz", "name": "New Zealand", "currency": "NZD"},
  {"code": "pw", "name": "Palau", "currency": "USD"},
  {"code": "pg", "name": "Papua New Guinea", "currency": "PGK"},
  {"code": "ws", "name": "Samoa", "currency": "WST"},
  {"code": "sb", "name": "Solomon Islands", "currency": "SBD"},
  {"code": "to", "name": "Tonga", "currency": "TOP"},
  {"code": "tv", "name": "Tuvalu", "currency": "AUD"},
  {"code": "vu", "name": "Vanuatu", "currency": "VUV"},
];

// final Map<String, List<Map<String, String>>> continentCountries = const {
//   "AS": asianCountries,
//   "EU": europeanCountries,
//   "AF": africanCountries,
//   "NA": northAmericanCountries,
//   "SA": southAmericanCountries,
//   "OC": oceaniaCountries
// };

final List<List<Map<String, String>>> continentList = const [
  asianCountries,
  europeanCountries,
  africanCountries,
  northAmericanCountries,
  southAmericanCountries,
  oceaniaCountries
];